### ISSUE TITLE
Stop removing all hidden files

### ISSUE THREAD

**Issue by marcoceppi** [juju/charm#201]
currently, charm strips all hidden files from a charm payload but this is removing valuable information that's not related to VCS.

This strips files, like .build.manifest, which are used to record the layers in the built charm artifact.

**Comment by ryan-beisner** [comment]
OpenStack Charms CI also needs the .build.manifest to survive charm push so that the published artifact possesses the manifest (and other .files).

I believe the relevant code is @ https://github.com/juju/charm/blob/v5/charmdir.go

**Comment by rogpeppe** [comment]
After some thought, we have decided that it might be good to exclude only an explicit set of files, including `.git`, `.bzr` and any other common VCS names, and only exclude them in the top level directory.
