### ISSUE TITLE
Declared series should be checked for consistency

### ISSUE THREAD

**Issue by wallyworld** [juju/charm#206]
When a charm declares what series are supported, these should be checked to ensure they all belong to the same OS. It is not allowed for a charm to say it supports xenial and win10 for example.

**Comment by marcoceppi** [comment]
But why couldn't it?

**Comment by wallyworld** [comment]
A discussion in the internal mailing list explains the reasons

**Comment by rogpeppe** [comment]
Currently the charm package has no knowledge of what series are allowed at all - it leaves that checking for the layer above, as it's really an operational constraint. If we agree with that decision (and it seems reasonable to me), that would mean this is more a bug in the deployment layer (juju) than in this package, so the bug should be raised there and closed here.

**Comment by marcoceppi** [comment]
That discussion is left unresolved.
