### ISSUE TITLE
Charm build: Leaking exception when charms begin with a number

### ISSUE THREAD

**Issue by kat-co** [juju/charm#217]
metadata.yaml:

``` yaml
name: 1605096
summary: Dummy charm to reproduce bug 1605096.
maintainer: Katherine Cox-Buday <katherine.cox-buday@canonical.com>
description: |
  N/A
tags:
  - debug
series:
  - trusty
  - xenial
resources:
  foo:
    type: file
    filename: foo.txt
    description: Debug resource.
```

``` bash
16:08> charm build
build: Composing into /home/kate/workspace/charm-1605096
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==1.11.2', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 579, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 461, in __call__
    self.find_or_create_repo()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 198, in find_or_create_repo
    self.create_repo()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 179, in create_repo
    self.target_dir = (self.repo / self.name)
  File "/usr/lib/python2.7/dist-packages/path.py", line 237, in __div__
    return self._next_class(self.module.join(self, rel))
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'int' object has no attribute 'startswith'
```

**Comment by marcoceppi** [comment]
Thanks for reporting this! A few things, while I think this bug exists in our latest, could you please verify that the same problem occurs in 2.1.2? Secondly, juju/charm is the charm golang package. [juju/charm-tools](http://github.com/juju/charm-tools) is where charm build the command lives.

**Comment by jrwren** [comment]
It is probably worth mentioning that charms cannot start with a digit.

From https://github.com/juju/names/blob/master/charm.go, 

    // CharmNameSnippet is a regular expression representing charm name
    CharmNameSnippet = "[a-z][a-z0-9]*(-[a-z0-9]*[a-z][a-z0-9]*)*"

So while the exception leak is bad, a nice fix might be  warning which states that charms must start with lowercase a-z

**Comment by johnsca** [comment]
This is not the repo for the `charm` command; please see https://github.com/juju/charm-tools instead.  This issue has been re-opened there.  Please close this one.
