### ISSUE TITLE
`charm build` - no such option: -d

### ISSUE THREAD

**Issue by jamesbeedy** [juju/charm#240]
Hitting this when running `charm build` https://paste.ubuntu.com/p/PmTBcjN86j/ using apt installed 
charm package. 
```
$ charm version
charm 2.1.1-0ubuntu1
charm-tools 2.1.2
```

**Comment by johnsca** [comment]
This is not the repo for the `charm` command.  Please see https://github.com/juju/charm-tools instead.

Also, the `charm` apt package is deprecated and very out of date.  I opened https://github.com/juju/charm-tools/issues/427 to track updating the apt package to either install the snap automatically or at least inform the user.
